### PR TITLE
Add sample native Gradle project

### PR DESCRIPTION
**Pull request by anthonydahanne**
## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [X] I have added an integration test, if necessary.
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by anthonydahanne** [comment]
I have a problem with this PR.

Using 100% gradle, worked fine, it built the native image

```
./gradlew bootBuildImage
```

But using `pack`, the `native-image` buildpack did not get any arguments

```
pack build applications/native-image \
  --builder paketobuildpacks/builder-jammy-tiny \
  --env BP_NATIVE_IMAGE=true
```

```
===> DETECTING
[detector] 7 of 15 buildpacks participating
[detector] paketo-buildpacks/ca-certificates   3.6.1
[detector] paketo-buildpacks/bellsoft-liberica 10.2.3
[detector] paketo-buildpacks/syft              1.30.0
[detector] paketo-buildpacks/gradle            7.2.1
[detector] paketo-buildpacks/executable-jar    6.7.1
[detector] paketo-buildpacks/spring-boot       5.25.0
[detector] paketo-buildpacks/native-image      5.11.0
[...]
[builder]       > Task :compileAotJava
[builder]       > Task :processAotResources
[builder]       > Task :aotClasses
[builder]       > Task :collectReachabilityMetadata
[builder]       > Task :bootJar
[builder]       > Task :jar
[builder]       > Task :assemble
[builder]       
[builder]       BUILD SUCCESSFUL in 36s
[builder]       9 actionable tasks: 9 executed
[builder] 
[builder]   Removing source code
[builder]   Restoring multiple artifacts
[builder] 
[builder] Paketo Buildpack for Executable JAR 6.7.1
[builder]   https://github.com/paketo-buildpacks/executable-jar
[builder] 
[builder] Paketo Buildpack for Native Image 5.11.0
[builder]   https://github.com/paketo-buildpacks/native-image
[builder]   Build Configuration:
[builder]     $BP_BINARY_COMPRESSION_METHOD                Compression mechanism used to reduce binary size. Options: `none` (default), `upx` or `gzexe`
[builder]     $BP_NATIVE_IMAGE                       true  enable native image build
[builder]     $BP_NATIVE_IMAGE_BUILD_ARGUMENTS             arguments to pass to the native-image command
[builder]     $BP_NATIVE_IMAGE_BUILD_ARGUMENTS_FILE        a file with arguments to pass to the native-image command
[builder]     $BP_NATIVE_IMAGE_BUILT_ARTIFACT              the built application artifact explicitly, required if building from a JAR
[builder]   Native Image: Contributing to layer
[builder]     Executing native-image --no-fallback -H:+StaticExecutableWithDynamicLibC -jar /workspace
[builder] Error: /workspace is a directory. (-jar requires a valid jarfile)
[builder] unable to invoke layer creator
[builder] unable to contribute native-image layer
[builder] error running build
[builder] exit status 1
[builder] ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle. This may be the result of using an untrusted builder: failed with status code: 51
```

Somehow, `boot` buildpack also did not build.

I'm wondering what got lost along the way... 

Any ideas @pivotal-david-osullivan @dmikusa ?

**Comment by dmikusa** [comment]
@anthonydahanne I suspect this is the problem with the pack build.

>[builder]   Restoring multiple artifacts

The build is detecting multiple artifacts when the gradle buildpack runs, and it can't build (at least not without more info).

When you build with Spring Boot build tools, it'll compile locally, take your JAR and run buildpacks against that so I suspect that's why it's working.

Normally, you'd set `jar -> enabled = false` so that it only has a single artifact as the output, but you have it set to true for another reason. You might need to set a `BP_GRADLE_BUILT_ARTIFACT` that is more specific so it only picks one artifact. 

```
jar {
    // see https://github.com/spring-projects/spring-boot/issues/33238
    enabled = true
}
```

**Comment by anthonydahanne** [comment]
@dmikusa thanks for your answer, that was it!

Actually, I can set `jar -> enabled = false` ; I have tested with both pure `gradle` build, with  `./gradlew bootBuildImage` and pure pack style, with:
```
pack build applications/native-image \
  --builder paketobuildpacks/builder-jammy-tiny \
  --env BP_NATIVE_IMAGE=true
```

So all in all, I should not have copied over this `jar` gradle configuration!

Good to go now, I've fixed the `buildle.gradle`!

**Comment by anthonydahanne** [comment]
just added the smoke test!

**Review by dmikusa — APPROVED** [review]

**Pull request merged**
