### PR TITLE
Update buildpack.toml to supported buildpack API version

### PR DESCRIPTION
**Pull request by ForestEckhardt**

### CODE REVIEW

**Review by dmikusa — APPROVED** [review]

**Comment by loewenstein** [comment]
I am a bit confused, isn't the current buildpack api level throughout Paketo 0.8 rather than 0.9 (or was it even 0.7)?

**Comment by ForestEckhardt** [comment]
@loewenstein I am not sure there is a decided upon Buildpack API standard. I am just bumping this higher so that we do not need to worry about it for a while as it is a buildpack that exists only for this sample.

**Comment by robdimsdale** [comment]
In general I like the idea of bumping to the lowest supported version that works for the buildpack and the lifecycle. It maximizes compatibility.

I agree that in this case it's essentially moot, but I think it's simpler to follow the same heuristics everywhere, rather than try to remember why this specific case is different.

**Comment by ForestEckhardt** [comment]
@robdimsdale I am happy to change it

**Comment by loewenstein** [comment]
There is also https://github.com/paketo-buildpacks/rfcs/issues/249 to figure out our policy for bumps.

**Review by dmikusa — APPROVED** [review]

**Pull request merged**
