### PR TITLE
Fix for issue #124

### PR DESCRIPTION
**Pull request by thehandsomezebra**
When doing the "Getting Started" (https://paketo.io/docs/), you may run into an error regarding "node" dependency version constraint "~10". Adjusting the package.json file to > allows for it to select an appropriate supported version.

#124 

## Summary
 When doing the "Getting Started" (https://paketo.io/docs/), you may run into an error regarding "node" dependency version constraint "~10".  Adjusting the package.json file to > allows for it to select an appropriate supported version.

## Use Cases

Successful "getting started" example.

## Checklist

* [X] I have viewed, signed, and submitted the Contributor License Agreement.
* [X] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.  _(not necessary)_
* [X] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [X] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by arjun024** [comment]
@thehandsomezebra LGTM but Paketo project needs you to sign the CLA to contribute. If you can sign the CLA, this change can be accepted. See https://github.com/paketo-buildpacks/.github/blob/main/CONTRIBUTING.md

**Comment by fg-j** [comment]
@thehandsomezebra I think something happened with the committer ID on your commit. Please amend the commit to allow the CLA check to run 🙂

**Comment by ryanmoran** [comment]
Hi @thehandsomezebra! It looks like the issue isn't with your signature on the CLA service, but with a few of the commits in this PR. When I look at the commits view, I can see some commits that look like they come from your GitHub account, and others that it appears are not attached to that same account. I believe the CLA service is reporting that it can't figure out who these other commits belong to and so it can't verify that the committer signed the CLA. Here is what I am seeing:

Screen Shot 2021-06-16 at 9 13 43 AM

I can see that the 1st, 4th, and 5th commits appear to be committed by you, just not associated with your GitHub account. Is it possible that you haven't configured `git` locally with the same email address that you use for your GitHub account?

**Comment by thehandsomezebra** [comment]
🤯  You're right. I did the commit on my work pc. My mistake. Hang tight

**Comment by thehandsomezebra** [comment]
(reverted and fixed appropriately with https://github.com/paketo-buildpacks/samples/pull/126

**Pull request closed without merging**
